### ISSUE TITLE
How to create a table?

### ISSUE THREAD

**Issue by Intevel** [betterwrite/pdfeasy#12]
How to create a table?

**Comment by Novout** [comment]
Table and forms are not yet supported. I'm likely to implement something similar to the [pdfkit-table](https://github.com/natancabral/pdfkit-table)

**Comment by Intevel** [comment]
Okay, thanks @Novout

**Comment by Novout** [comment]
This is now possible in https://github.com/betterwrite/pdfeasy/releases/tag/v1.1.0

**Comment by Intevel** [comment]
> This is now possible in https://github.com/betterwrite/pdfeasy/releases/tag/v1.1.0

Nice ❤️

**Comment by valentinhttr** [comment]
@Novout hi, it would be great to be able to generate a (simplified) table using HTML code directly.
